import { PALETTE, scoreColor, scoreLabel, withAlpha } from "../theme";
import { donut, esc, sheet } from "../primitives";
import type { ReportContext } from "../context";

/** Page 1 — full-bleed dark. One idea: this is your report. */
export function coverSheet(ctx: ReportContext): string {
  const { report, brandName, accent, logoSrc, date, time } = ctx;
  const color = scoreColor(report.score);

  const brandLockup = `<div style="display:flex;align-items:center;gap:9pt;">
    ${logoSrc ? `<img src="${logoSrc}" style="height:22pt;width:auto;max-width:110pt;object-fit:contain;" alt="${esc(brandName)}"/>` : ""}
    <span style="font-family:'Space Grotesk',sans-serif;font-weight:700;font-size:12pt;letter-spacing:0.02em;">${esc(brandName)}</span>
  </div>`;

  return sheet(
    `${brandLockup}

    <div style="flex:1 1 auto;display:flex;flex-direction:column;justify-content:center;padding:18pt 0;">
      <div class="eyebrow" style="color:${accent};">Growth Leak Report</div>

      <h1 class="display" style="margin-top:10pt;color:${PALETTE.onDark};word-break:break-word;">
        ${esc(report.domain)}
      </h1>

      <p style="margin-top:12pt;font-size:12pt;line-height:1.5;color:${PALETTE.onDarkMuted};max-width:130mm;">
        ${esc(report.businessUnderstanding.primaryGoal)}
      </p>

      <div style="height:1pt;background:${withAlpha(accent, 0.4)};margin:22pt 0;width:70mm;"></div>

      <div style="display:flex;align-items:center;gap:24pt;">
        ${donut(report.score, color, 132, true)}
        <div>
          <div class="eyebrow" style="color:${PALETTE.onDarkMuted};">Ghost Score</div>
          <div style="font-family:'Space Grotesk',sans-serif;font-size:24pt;font-weight:700;color:${color};margin-top:5pt;line-height:1.1;">
            ${esc(scoreLabel(report.score))}
          </div>
          <div style="margin-top:9pt;font-size:9.5pt;color:${PALETTE.onDarkMuted};">
            ${report.leaks.length} finding${report.leaks.length === 1 ? "" : "s"} found
          </div>
        </div>
      </div>
    </div>

    <div style="display:flex;justify-content:space-between;align-items:flex-end;font-size:8pt;color:${PALETTE.onDarkMuted};letter-spacing:0.06em;">
      <span>${esc(report.url)}</span>
      <span>${esc(date)} · ${esc(time)}</span>
    </div>`,
    { dark: true },
  );
}

/** Final page — methodology, caveats, contact. */
export function backCoverSheet(ctx: ReportContext): string {
  const { report, brandName, accent, logoSrc, contactParts, date } = ctx;

  const confidence = report.lowConfidence && report.confidenceNote
    ? `<div style="margin-top:20pt;border:0.75pt solid ${withAlpha("#F0D98A", 0.5)};background:${withAlpha("#F0D98A", 0.08)};border-radius:4pt;padding:11pt 13pt;">
         <div class="eyebrow" style="color:#E3C46B;">Limited visibility</div>
         <p style="margin:5pt 0 0;font-size:9pt;line-height:1.5;color:${PALETTE.onDarkMuted};">${esc(report.confidenceNote)}</p>
       </div>`
    : "";

  const contact = contactParts.length
    ? `<div style="margin-top:9pt;font-size:9.5pt;color:${PALETTE.onDarkMuted};">${contactParts.map((c) => esc(c)).join(" · ")}</div>`
    : "";

  return sheet(
    `<div class="eyebrow" style="color:${accent};">Methodology</div>

    <div style="flex:1 1 auto;padding-top:16pt;">
      <h2 style="font-size:20pt;line-height:1.2;color:${PALETTE.onDark};max-width:130mm;">
        How this report was produced
      </h2>

      <p style="margin-top:14pt;font-size:9.5pt;line-height:1.6;color:${PALETTE.onDarkMuted};max-width:135mm;">
        Ghost crawled ${esc(report.domain)} and sent AI shoppers through it with distinct goals and
        personalities — checking pricing, trust signals, navigation and speed the way real customers do.
        Every finding in this report is traced to something observed on the site. The Ghost Score is
        computed from weighted, individually-evidenced checks, listed in full in the score evidence pages.
      </p>

      <p style="margin-top:10pt;font-size:9.5pt;line-height:1.6;color:${PALETTE.onDarkMuted};max-width:135mm;">
        Where evidence could not be verified, this report says so rather than assuming. Unknown values are
        shown as — and are never counted as zero.
      </p>

      ${confidence}
    </div>

    <div style="border-top:0.75pt solid rgba(255,255,255,0.14);padding-top:14pt;">
      <div style="display:flex;align-items:center;gap:9pt;">
        ${logoSrc ? `<img src="${logoSrc}" style="height:20pt;width:auto;max-width:100pt;object-fit:contain;" alt="${esc(brandName)}"/>` : ""}
        <span style="font-family:'Space Grotesk',sans-serif;font-weight:700;font-size:11pt;">${esc(brandName)}</span>
      </div>
      ${contact}
      <div style="margin-top:12pt;font-size:7.5pt;letter-spacing:0.1em;text-transform:uppercase;color:${PALETTE.faint};">
        Generated by Ghost · ${esc(date)}
      </div>
    </div>`,
    { dark: true },
  );
}
