"use client";
import { Check } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { copy } from "@/lib/copy";
import { useStartScan } from "@/hooks/useStartScan";
export function Pricing() {
  const start=useStartScan();
  return <section id="pricing" className="section-pad product-section"><div className="product-container"><p className="eyebrow mb-4">Audit options</p><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="display-lg font-medium">The right depth<br />for your next decision.</h2><p className="max-w-md text-sm text-muted-light">Ghost is in early access. Approved accounts can run Full Intelligence audits while payments are offline. The plans below describe the planned paid offering.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{copy.landing.pricing.tiers.map(tier=><article key={tier.id} className={`surface-panel flex flex-col p-6 ${tier.highlighted?'border-violet/60':''}`}><p className="mb-4 text-[11px] font-medium uppercase tracking-wider text-violet">{tier.highlighted?'Most complete':tier.id==='agency_2999'?'For client work':tier.id==='free'?'A first look':'For one website'}</p><h3 className="font-heading text-xl font-semibold">{tier.name}</h3><p className="mt-4 flex items-baseline gap-2"><span className="font-heading text-3xl font-medium">{tier.price}</span><span className="text-xs text-muted">{tier.cadence}</span></p><p className="mt-4 text-sm text-muted-light">{tier.description}</p><ul className="my-6 flex-1 space-y-3">{tier.features.map(f=><li key={f} className="flex items-start gap-2 text-xs leading-relaxed text-muted-light"><Check aria-hidden className="mt-0.5 h-3.5 w-3.5 shrink-0 text-violet" />{f}</li>)}</ul><Button onClick={start} variant={tier.highlighted?'primary':'secondary'}>Request access</Button></article>)}</div><p className="mt-5 text-xs text-muted">Planned prices in INR, exclusive of GST. No payment is collected during early access.</p></div></section>;
}
