/**
 * Smoke test: generate a sample Ghost report PDF and upload to Supabase Storage.
 *
 * Usage (from Ghost/):
 *   set -a && source .env.local && set +a && npx tsx scripts/test-pdf-upload.ts
 */

import { createMockReport } from "../src/lib/mock-data";
import { generateGhostReportPdf } from "../src/lib/report/reportPdf";
import { uploadMissionPdf } from "../src/lib/storage/supabase";
import type { CompetitorIntelligence } from "../src/lib/competitor-intelligence/types";
import { TAXONOMY_VERSION } from "../src/lib/competitor-intelligence/feature-taxonomy";
import { INTELLIGENCE_VERSION } from "../src/lib/competitor-intelligence/types";

function sampleMarketIntelligence(missionId: string): CompetitorIntelligence {
  return {
    missionId,
    intelligenceVersion: INTELLIGENCE_VERSION,
    generatedAt: new Date().toISOString(),
    taxonomyVersion: TAXONOMY_VERSION,
    market_definition: {
      category: "Sample D2C skincare",
      geography: "India",
      buyerGoal: "Find effective products with visible results",
    },
    search_strategy: {
      queries: ["sample skincare india"],
      sourcesUsed: ["test-script"],
    },
    competitorSummaries: [
      {
        crawlPackId: "sample-1",
        name: "Sample Competitor A",
        canonicalUrl: "https://competitor-a.example",
        relevanceScore: 88,
        qualityScore: 72,
        topStrengths: ["Strong social proof", "Clear ingredient lists"],
        weaknesses: ["Slow checkout", "Limited returns info"],
        evidenceHighlights: ["Homepage highlights clinical trials"],
      },
    ],
    owner_features: {
      siteUrl: "https://example.com",
      siteName: "Example Store",
      extractedAt: new Date().toISOString(),
      features: {},
    },
    market_expectations: {
      competitorCount: 1,
      expectations: [
        {
          featureId: "social_proof",
          marketScore: 78,
          competitorCount: 1,
          criteria: [],
          marketEvidence: "Sample evidence for PDF smoke test.",
        },
      ],
    },
    market_gaps: [
      {
        gap: "Missing verified customer reviews above the fold",
        evidence: "Competitors show star ratings and review counts in hero sections.",
        impact: "Buyers may doubt product quality before scrolling.",
        recommendation: "Add a review summary widget to the homepage hero.",
        featureId: "social_proof",
        dimension: "trust",
        gapType: "weaker_than_market",
        priority: "high",
        prevalence: 0.8,
        competitorCount: 1,
        ownerScore: 42,
        marketScore: 78,
        scoreDelta: 36,
        missingCriteria: ["Review count visible on homepage"],
      },
    ],
    limitations: ["Generated by test-pdf-upload.ts — not real crawl data."],
  };
}

async function main() {
  const missionId = `pdf-upload-test-${Date.now()}`;
  const url = "https://example.com";
  const domain = "example.com";

  console.log("1. Checking Supabase env…");
  for (const key of ["SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY"]) {
    if (!process.env[key]) {
      throw new Error(`Missing ${key}. Run: set -a && source .env.local && set +a && npx tsx scripts/test-pdf-upload.ts`);
    }
    console.log(`   ✓ ${key} is set`);
  }
  const bucket = process.env.SUPABASE_PDF_BUCKET ?? "ghost-reports";
  console.log(`   ✓ bucket: ${bucket}`);

  console.log("\n2. Generating sample PDF (mock report + market intelligence)…");
  const report = createMockReport(url, domain);
  report.id = missionId;
  const marketIntelligence = sampleMarketIntelligence(missionId);
  const pdfBytes = await generateGhostReportPdf(report, undefined, marketIntelligence);
  console.log(`   ✓ PDF generated (${pdfBytes.byteLength.toLocaleString()} bytes)`);

  console.log("\n3. Uploading to Supabase Storage…");
  const uploaded = await uploadMissionPdf({ missionId, domain, pdfBytes: pdfBytes });
  console.log(`   ✓ bucket: ${uploaded.bucket}`);
  console.log(`   ✓ path:   ${uploaded.path}`);
  console.log(`   ✓ url:    ${uploaded.publicUrl}`);

  console.log("\n4. Verifying public URL is reachable…");
  const res = await fetch(uploaded.publicUrl, { method: "HEAD" });
  const contentType = res.headers.get("content-type") ?? "";
  const contentLength = res.headers.get("content-length") ?? "unknown";

  if (!res.ok) {
    throw new Error(`Public URL returned HTTP ${res.status} ${res.statusText}`);
  }
  if (!contentType.includes("pdf") && !contentType.includes("octet-stream")) {
    console.warn(`   ⚠ unexpected content-type: ${contentType}`);
  } else {
    console.log(`   ✓ content-type: ${contentType}`);
  }
  console.log(`   ✓ content-length: ${contentLength}`);
  console.log("\n✅ PDF upload to Supabase succeeded.");
}

main().catch((err) => {
  console.error("\n❌ PDF upload test failed:");
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
